platform :ios, '11.0'
use_frameworks!

target 'OxeNetworking_Example' do
  pod 'OxeNetworking', :path => '../'
  pod 'OxeNetworking/Rx', :path => '../'

  target 'OxeNetworking_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # This works around a unit test issue introduced in Xcode 10.
      # We only apply it to the Debug configuration to avoid bloating the app size
      if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
      end
    end
  end
end
